# Generated by Django 3.2.4 on 2021-07-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField(verbose_name='Nombre del curso')),
                ('horas', models.FloatField(max_length=1, verbose_name='Horas del curso')),
                ('aprobado', models.BooleanField(verbose_name='Marca solo si aprobaste')),
                ('comentario', models.CharField(max_length=100, verbose_name='Comentarios sobre el curso')),
                ('inicio', models.DateField(verbose_name='Inicio del curso')),
                ('fin', models.DateField(verbose_name='Fin del cuerso')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
