# Generated by Django 3.2.4 on 2021-07-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='comentario',
            field=models.TextField(verbose_name='Comentarios sobre el curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='curso',
            field=models.CharField(max_length=20, verbose_name='Nombre del curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='horas',
            field=models.FloatField(verbose_name='Horas del curso'),
        ),
    ]
