# Generated by Django 3.2.4 on 2021-07-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
