# Generated by Django 3.2.4 on 2021-07-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='comentario',
        ),
    ]
