# Generated by Django 3.2.4 on 2021-07-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_cursos_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='curso',
            new_name='materia',
        ),
    ]
