# Generated by Django 3.2.4 on 2021-08-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_comentarioform_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('mat', models.TextField(verbose_name='Curso')),
                ('tur', models.TextField(verbose_name='Turno')),
                ('matricula', models.TextField(verbose_name='Matricula')),
                ('calif', models.TextField(verbose_name='Calificación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Curso',
                'verbose_name_plural': 'Comentarios Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
